Task101

diff --git a/0x00-python-hello_world/101-compile b/0x00-python-hello_world/101-compile
--- a/0x00-python-hello_world/101-compile
+++ b/0x00-python-hello_world/101-compile
@@ -1,2 +1,25 @@
 #!/bin/bash
-python3 -m py_compile $PYFILE; mv ./__pycache__/*.pyc "${PYFILE}c"
+
+# Check if the PYFILE environment variable is set
+if [ -z "$PYFILE" ]; then
+    echo "Error: PYFILE environment variable is not set."
+    exit 1
+fi
+
+# Get the filename without extension
+filename=$(basename -- "$PYFILE")
+filename_noext="${filename%.*}"
+
+# Set the output filename with .pyc extension
+output_filename="$filename_noext.pyc"
+
+# Compile the Python script
+python -m py_compile "$PYFILE"
+
+# Check if compilation was successful
+if [ $? -eq 0 ]; then
+    echo "Compilation successful. Output file: $output_filename"
+else
+    echo "Compilation failed."
+    exit 1
+fi
